name: CD

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn
      - run: yarn build
      # - run: yarn prettier-check
      # - run: yarn lint
      # - run: yarn test
      - run: echo "TODO PUBLISH PACKAGE HERE"
